version: '3'
services:
  streamlit:
    build: ./my_notebook
    image: streamlit
    user: jovyan
    ports:
      - 8888:8888
      - 8501:8501
    environment:
      - DISPLAY=:99
      - USE_HEADLESS_BROWSER=1
    volumes:
      - .:/home/jovyan/work
