on:
  push:
    branches:
      - main
      - master
      - cpp
  pull_request:
    branches:
      - main
      - master

name: build_test

jobs:
  build_test:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      USE_HEADLESS_BROWSER: 1
      DISPLAY: :99
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - uses: browser-actions/setup-chrome@latest
      - uses: nanasess/setup-chromedriver@master

      - name: Install python package dependencies
        run: |
          sudo apt-get install -y firefox firefox-geckodriver
          sudo python -m pip install autopep8 check-manifest coverage find_libpython flake8 matplotlib mypy numpy opencv-python pandas pep8 pipenv pylint pytest pytest-cov pyyaml py_pkg scipy seleniumbase sphinx sphinx_rtd_theme streamlit types-PyYAML types-requests
          sudo python -m pip install chromedriver-binary-auto
          sudo apt-get install -y build-essential cmake net-tools python3-dev unzip wget
          sudo wget https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_77_0.tar.gz
          sudo tar xzf boost_1_77_0.tar.gz

      - name: Install Boost C++ libraries
        working-directory: ./boost_1_77_0
        run: |
          sudo ./bootstrap.sh --with-libraries=python --with-python=python3.9 --with-python-version=3.9
          sudo ./b2 install cxxflags=-fPIC address-model=64 threading=multi link=static runtime-link=shared variant=release -j4 --prefix=/opt/boost_1_77_0

      - name: Make aliases
        continue-on-error: true
        run: |
          sudo test -d /opt/boost || ln -s /opt/boost_1_77_0 /opt/boost
          sudo test -f /opt/boost_1_77_0/lib/libboost_python.a || ln -s /opt/boost_1_77_0/lib/libboost_python*.a /opt/boost_1_77_0/lib/libboost_python.a

      - name: Install Google Test
        run: |
          sudo wget https://github.com/google/googletest/archive/refs/heads/main.zip
          sudo unzip main.zip
          sudo mv googletest-* /opt/googletest

      - name: Install this package
        run: |
          sudo python setup.py bdist_wheel
          sudo python -m pip install dist/*.whl

      - name: Install Xvfb
        run: |
          sudo apt-get install -y xvfb

      - name: Run Xvfb
        continue-on-error: true
        run: |
          sudo Xvfb -ac -screen 0 1024x768x24 :99 &

      - name: Start Streamlit Server
        continue-on-error: true
        run: |
          sudo yes "" | streamlit run launcher/launch.py &

      - name: List processes and ports
        continue-on-error: true
        run: |
          ps aux
          netstat -l
          wget http://localhost:8501

      - name: Check C++ code
        working-directory: ./src/dist
        run: |
          make test
          mkdir -p build

      - name: Check cmake
        working-directory: ./src/dist/build
        run: |
          cmake .. -DPYTHON_INCLUDE_DIR=$(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())") -DPYTHON_LIBRARY=$(python -m find_libpython)
          make
          make test

      - name: Check backend
        run: |
          pytest tests/test_nbinom.py

      - name: Check frontend
        run: |
          pytest tests/test_ui.py || pytest tests/test_ui.py || pytest tests/test_ui.py || pytest tests/test_ui.py

      - name: Reinstall this package to measure coverage
        run: |
          python -m pip install -e .

      - name: Make documents
        run: |
          sphinx-quickstart -q -p nbinomPlotPy -a "Zettsu Tatsuya"
          patch < patch/conf.py.diff
          patch < patch/index.rst.diff
          make html
