on:
  push:
    branches:
      - main
      - master
      - cpp
  pull_request:
    branches:
      - main
      - master

name: build_test

jobs:
  build_test:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      USE_HEADLESS_BROWSER: 1
      DISPLAY: :99
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - uses: browser-actions/setup-firefox@latest
      - uses: browser-actions/setup-chrome@latest
      - uses: browser-actions/setup-geckodriver@latest
      - uses: nanasess/setup-chromedriver@master

      - name: Install python package dependencies
        run: |
          python -m pip install autopep8 check-manifest coverage flake8 matplotlib mypy numpy opencv-python pandas pep8 pipenv pylint pytest pytest-cov pyyaml py_pkg scipy seleniumbase sphinx sphinx_rtd_theme streamlit types-PyYAML types-requests
          python -m pip install chromedriver-binary-auto

      - name: Install this package
        run: |
          python -m pip install .

      - name: Install C++ and testing packages
        run: |
          sudo apt-get install -y build-essential python3-dev unzip wget
          sudo wget https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_77_0.tar.gz
          sudo tar xzf boost_1_77_0.tar.gz
          sudo cd boost_1_77_0 && ./bootstrap.sh --with-libraries=python --with-python=python3.9 --with-python-version=3.9 && ./b2 install cxxflags=-fPIC address-model=64 threading=multi link=static runtime-link=shared variant=release -j4 --prefix=/opt/boost_1_77_0
          sudo wget https://github.com/google/googletest/archive/refs/heads/main.zip
          sudo unzip main.zip
          sudo mv googletest-* /opt/googletest

      - name: Start Streamlit Server
        continue-on-error: true
        run: |
          yes "" | streamlit run launcher/launch.py &

      - name: Install Xvfb
        run: |
          sudo apt-get install -y xvfb

      - name: Run Xvfb
        continue-on-error: true
        run: |
          Xvfb -ac -screen 0 1024x768x24 :99 &
          sleep(10)

      - name: Check C++ code
        run: |
          cd src/dist; make test; cd ../..

      - name: Check backend
        run: |
          pytest tests/test_nbinom.py

      - name: Check frontend
        run: |
          pytest tests/test_ui.py || pytest tests/test_ui.py || pytest tests/test_ui.py || pytest tests/test_ui.py

      - name: Make documents
        run: |
          sphinx-quickstart -q -p nbinomPlotPy -a "Zettsu Tatsuya"
          patch < patch/conf.py.diff
          patch < patch/index.rst.diff
          make html
