on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: nbinomPlotPy

jobs:
  nbinomPlotPy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      USE_HEADLESS_BROWSER: 1
      DISPLAY: :99
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - uses: browser-actions/setup-firefox@latest
      - uses: browser-actions/setup-chrome@latest
      - uses: browser-actions/setup-geckodriver@latest
      - uses: nanasess/setup-chromedriver@master

      - name: Install python package dependencies
        run: |
          python -m pip install autopep8 check-manifest coverage flake8 matplotlib mypy numpy opencv-python pandas pep8 pipenv pylint pytest pytest-cov pyyaml pyyaml py_pkg scipy seleniumbase sphinx sphinx_rtd_theme streamlit types-PyYAML types-requests

      - name: Install this package
        run: |
          python -m pip install .

      - name: Start Streamlit Server
        continue-on-error: true
        run: |
          yes "" | streamlit run launcher/launch.py &

      - name: Install Xvfb
        run: |
          sudo apt-get install xvfb

      - name: Run Xvfb
        continue-on-error: true
        run: |
          Xvfb -ac -screen 0 1920x1080x24 :99 &
          sleep(10)

      - name: Check backend
        run: |
          pytest tests/test_nbinom.py

      - name: Check frontend
        run: |
          pytest tests/test_ui.py
