on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: nbinomPlotPy

jobs:
  nbinomPlotPy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: browser-actions/setup-firefox@latest
      - uses: browser-actions/setup-chrome@latest
      - uses: browser-actions/setup-geckodriver@latest
      - uses: nanasess/setup-chromedriver@master

      - name: Install this package
        run: |
          python -m pip install .
          python -m pip install autopep8 check-manifest coverage flake8 matplotlib mypy numpy opencv-python pandas pep8 pipenv pylint pytest pytest-cov pyyaml pyyaml py_pkg scipy seleniumbase sphinx sphinx_rtd_theme streamlit types-PyYAML types-requests

      - name: Start Streamlit Server
        run: |
          yes "" | streamlit run launcher/launch.py &
          sleep(10)

      - name: Check
        run: |
          pytest
